import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";
import { getCurrentSession } from "@/actions/auth";
import { SanityLive } from "@/sanity/lib/live";
import { getAllCategories } from "@/sanity/lib/client";
import HeaderCategorySelector from "@/components/layout/HeaderCategorySelector";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = async ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  const { user } = await getCurrentSession();
  const  categories =  await getAllCategories();

  return (
      <html lang='en'>
          <body className={`${inter.className} antialiased bg-white min-h-[125vh]`}>
              <Header 
                  user={user}
                  categorySelector={<HeaderCategorySelector />}
              />
              {/* <Script
                  src='https://cloud.umami.is/script.js'
                  data-website-id='(YOUR UMAMI WEBSITE ID)'
                  strategy='beforeInteractive'
              /> */}

              {/* <Suspense>
                  <AnalyticsTracker
                      user={user}
                  />
              </Suspense> */}

              {children}

              {/* <Cart />*/}
              <SanityLive /> 
          </body>
      </html>
  );
};

export default RootLayout;
